version: "3.9"

networks:
  easyfood-network:
    driver: bridge

services:
  easyfood-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "32674463849"
    ports:
      - "13306:3306"
    networks:
      - easyfood-network
      
  easyfood-redis:
    image: redis:6.2.1-alpine
    networks:
      - easyfood-network

  easyfood-api:
    image: easyfood-api
    command: ["/wait-for-it.sh", "easyfood-mysql:3306", "-t", "30", "--", "java", "-jar", "easyfood.jar"]
    environment:
      DB_HOST: easyfood-mysql
      SPRING_SESSION_STORE_TYPE: redis
      SPRING_REDIS_HOST: easyfood-redis
      SPRING_PROFILES_ACTIVE: development
    networks:
      - easyfood-network
    depends_on:
      - easyfood-mysql
      
  easyfood-proxy:
    build: ./nginx
    image: easyfood-proxy
    ports:
      - "80:80"
    networks:
      - easyfood-network
    depends_on:
      - easyfood-api